language: node_js
node_js:
- '0.12'
before_deploy: npm run build
cache: bundler
deploy:
  provider: s3
  access_key_id: AKIAJKPPTVTSBW2NTUMA
  secret_access_key:
    secure: d8Sp08e0sVg1EDB2O1EIBUQpyUkugH2zBWCchFTua9Bd3XAmg0xIUgYXeOKgb5zErAu511R7AmJ6b2rUFBEFKwlNN2ZVizzEcgF7NdadJxchuXGpqn6kwGQszcCDnLJW/XA5m0kLmdN8L2bro7LelA2FKq2RiNZHs/oCObj/4x0=
  bucket: demo.crossb.io
  region: eu-west-1
  acl: public-read
  detect_encoding: true
  skip_cleanup: true
  local-dir: build
  on:
    repo: greenify/crossbio
